In [1]:
print("hii w_e")

hii w_e


#Word Embedding Techniques using Embedding Layer in Keras

In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:

sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
voc_size=10000

#One Hot Representation

In [6]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[333, 585, 2751, 265], [333, 585, 2751, 7048], [333, 7351, 2751, 562], [7200, 969, 68, 8997, 3515], [7200, 969, 68, 8997, 1476], [1439, 333, 6483, 2751, 5296], [7526, 8795, 9256, 8997]]


#Word Embedding Represntation

In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0  333  585 2751  265]
 [   0    0    0    0  333  585 2751 7048]
 [   0    0    0    0  333 7351 2751  562]
 [   0    0    0 7200  969   68 8997 3515]
 [   0    0    0 7200  969   68 8997 1476]
 [   0    0    0 1439  333 6483 2751 5296]
 [   0    0    0    0 7526 8795 9256 8997]]


In [10]:
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [14]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 202ms/step
[[[-0.01718475 -0.02685686  0.01631076 -0.03037059 -0.04449051
    0.00388757  0.03097706  0.00594557 -0.04279874  0.02799252]
  [-0.01718475 -0.02685686  0.01631076 -0.03037059 -0.04449051
    0.00388757  0.03097706  0.00594557 -0.04279874  0.02799252]
  [-0.01718475 -0.02685686  0.01631076 -0.03037059 -0.04449051
    0.00388757  0.03097706  0.00594557 -0.04279874  0.02799252]
  [-0.01718475 -0.02685686  0.01631076 -0.03037059 -0.04449051
    0.00388757  0.03097706  0.00594557 -0.04279874  0.02799252]
  [ 0.00163348 -0.04030255  0.04712503 -0.03390793  0.01064696
   -0.04164783 -0.00123707 -0.04091544  0.01847727 -0.0340088 ]
  [-0.03511216  0.04980016  0.03068936  0.00012436 -0.04915825
   -0.04279266  0.00667348 -0.00209663  0.04265522  0.03021843]
  [ 0.02224186  0.01045293 -0.00599249  0.00337641  0.04112737
   -0.03574823 -0.04421039  0.02693081 -0.00469809 -0.02240018]
  [-0.03617913  0.04089143  0.0419747   0.04926163 -0.0008

In [15]:
embedded_docs[0]

array([   0,    0,    0,    0,  333,  585, 2751,  265], dtype=int32)

In [16]:
print(model.predict(embedded_docs)[0])


1/1 [==============================] - 0s 18ms/step
[[-0.01718475 -0.02685686  0.01631076 -0.03037059 -0.04449051  0.00388757
   0.03097706  0.00594557 -0.04279874  0.02799252]
 [-0.01718475 -0.02685686  0.01631076 -0.03037059 -0.04449051  0.00388757
   0.03097706  0.00594557 -0.04279874  0.02799252]
 [-0.01718475 -0.02685686  0.01631076 -0.03037059 -0.04449051  0.00388757
   0.03097706  0.00594557 -0.04279874  0.02799252]
 [-0.01718475 -0.02685686  0.01631076 -0.03037059 -0.04449051  0.00388757
   0.03097706  0.00594557 -0.04279874  0.02799252]
 [ 0.00163348 -0.04030255  0.04712503 -0.03390793  0.01064696 -0.04164783
  -0.00123707 -0.04091544  0.01847727 -0.0340088 ]
 [-0.03511216  0.04980016  0.03068936  0.00012436 -0.04915825 -0.04279266
   0.00667348 -0.00209663  0.04265522  0.03021843]
 [ 0.02224186  0.01045293 -0.00599249  0.00337641  0.04112737 -0.03574823
  -0.04421039  0.02693081 -0.00469809 -0.02240018]
 [-0.03617913  0.04089143  0.0419747   0.04926163 -0.00087273  0.01518393